/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.opertaions;

import org.junit.jupiter.api.*;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FilerOperationTest {
    static FilterOperation fl;
    static List<String> list;
    @BeforeAll
    public static void init(){
        list = Arrays.asList("Nagaraju","Mahesh","Somu","Software","","Java8Features","filter");
        fl=new FilterOperation();
    }
    @Test
    @Order(1)
    public void deafultCaseTest() {
        System.out.println("Default Test Case---");
        List<String>names=fl.filterNames(list,"");
        assertEquals(2,names.size());
        names.stream().forEach(s->System.out.println(s));
    }
    @Test
    @Order(2)
    public void choiceTest1() {
        System.out.println("m Char Test Case---");
        List<String>names=fl.filterNames(list,"m");
        names.stream().forEach(s->System.out.println(s));
        assertEquals(1,names.size());

    }
    @Test
    @Order(2)
    public void choiceTest2() {
        System.out.println("l Char Test Case---");
        List<String>names=fl.filterNames(list,"l");
        names.stream().forEach(s->System.out.println(s));
        assertEquals(3,names.size());

    }


}

